# Docker-specific configuration
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:${MONGODB_URI:mongodb://localhost:27017/zeepark}}
spring.data.mongodb.database=zeepark
logging.level.root=INFO
logging.level.com.ekwe_hub=DEBUG
