spring.application.name=zeePark
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/zeepark}
spring.data.mongodb.auto-index-creation=true
spring.threads.virtual.enabled=true
server.port=${PORT:8181}
server.error.include-message=always
server.error.include-binding-errors=always
logging.level.com.ekwe_hub=DEBUG
logging.level.org.springframework.data.mongodb=INFO

spring.main.allow-bean-definition-overriding=true


# Payment Gateway Config
payment.paypal.client-id=${PAYPAL_CLIENT_ID:}
payment.paypal.secret=${PAYPAL_SECRET:}
payment.paypal.mode=${PAYPAL_MODE:sandbox}
payment.mastercard.api-key=${MASTERCARD_API_KEY:}
payment.mastercard.merchant-id=${MASTERCARD_MERCHANT_ID:}

# Flutterwave
payment.flutterwave.public-key=${FLW_PUBLIC_KEY:}
payment.flutterwave.secret-key=${FLW_SECRET_KEY:}
payment.flutterwave.redirect-url=${FLW_REDIRECT_URL:zeepark://payment/success}