# Docker-specific configuration
spring.data.mongodb.uri=mongodb://zeepark:your_secure_password_here@zeepark-mongodb:27017/zeepark?authSource=admin
spring.data.mongodb.database=zeepark
logging.level.root=INFO
logging.level.com.ekwe_hub=DEBUG
